# Generated by Django 5.2.6 on 2026-03-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TRMHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Date of the exchange rate', unique=True)),
                ('valor_cop', models.DecimalField(decimal_places=2, help_text='USD to COP exchange rate value', max_digits=10)),
                ('fuente', models.CharField(default='superfinanciera', help_text='Source of the exchange rate (e.g. superfinanciera, banco_central)', max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
            ],
            options={
                'verbose_name': 'TRM History',
                'verbose_name_plural': 'TRM Histories',
                'ordering': ['-fecha'],
            },
        ),
    ]
