# Generated by Django 5.2.6 on 2026-03-15 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_campoproducto_proveedor_tipoproducto_and_more'),
        ('sales', '0002_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('tipo', models.CharField(choices=[('compra_externa', 'External Purchase'), ('canje_cliente', 'Trade-in from Client')], default='compra_externa', help_text='Type of purchase: external or trade-in', max_length=20)),
                ('numero_orden', models.CharField(help_text='Order number from supplier or internal reference', max_length=100)),
                ('numero_tracking', models.CharField(blank=True, help_text='Tracking number for shipment (optional)', max_length=100, null=True)),
                ('costo_compra', models.DecimalField(decimal_places=2, help_text='Purchase cost (typically in USD)', max_digits=14)),
                ('costo_importacion', models.DecimalField(blank=True, decimal_places=2, help_text='Import costs if applicable (optional)', max_digits=14, null=True)),
                ('impuesto_importacion', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto-calculated as 2% of costo_compra', max_digits=14)),
                ('cliente', models.ForeignKey(blank=True, help_text='Customer (used for trade-in purchases)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='sales.cliente')),
                ('proveedor', models.ForeignKey(blank=True, help_text='Supplier (used for external purchases)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='products.proveedor')),
                ('unidad_producto', models.ForeignKey(help_text='Product unit this purchase order refers to', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='products.unidadproducto')),
                ('usuario_ultima_modificacion', models.ForeignKey(help_text='Last user who modified this purchase order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-id'],
            },
        ),
    ]
