# Generated by Django 5.2.6 on 2026-03-17 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_campoproducto_proveedor_tipoproducto_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='condicion',
            field=models.CharField(choices=[('nuevo', 'New'), ('open_box', 'Open Box'), ('refurbished', 'Refurbished'), ('usado', 'Used')], default='nuevo', help_text='Physical condition of the unit being created', max_length=20),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling price for created unit; if blank, auto-calculated via formula', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Product being purchased', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='products.producto'),
        ),
    ]
