# Generated by Django 5.2.6 on 2026-03-17 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_campoproducto_proveedor_tipoproducto_and_more'),
        ('purchases', '0005_remove_ordencompra_variante_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='estado_logistico',
            field=models.CharField(choices=[('viajando', 'In Transit'), ('en_oficina_importadora', 'At Importer Office'), ('en_oficina', 'In Store')], default='viajando', help_text='Logistic status of the purchase', max_length=30),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='serial_generado',
            field=models.CharField(blank=True, help_text='Serial number for the unit (auto-generated if not provided)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='unidad_producto',
            field=models.OneToOneField(blank=True, help_text='Specific unit created for this purchase order (auto-created on save)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orden_compra', to='products.unidadproducto'),
        ),
    ]
