# Generated by Django 5.2.6 on 2026-03-24 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_campoproducto_required_and_more'),
        ('purchases', '0007_remove_tipo_cliente_serial_generado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Supplier for this purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='products.proveedor'),
        ),
    ]
