# Generated by Django 5.2.6 on 2026-04-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_ordencompra_porcentaje_impuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='condicion',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('open_box', 'Open Box'), ('refurbished', 'Reacondicionado'), ('usado', 'Usado')], default='nuevo', help_text='Physical condition of the unit being created', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='impuesto_importacion',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculated as porcentaje_impuesto% of costo_compra (set via serializer)', max_digits=14),
        ),
    ]
