# Generated by Django 5.2.6 on 2026-04-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_alter_ordencompra_condicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_compra',
            field=models.DateField(blank=True, help_text='Real transaction date (editable). Defaults to creation date if omitted.', null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_en_oficina',
            field=models.DateTimeField(blank=True, help_text="Timestamp when estado_logistico transitioned to 'en_oficina'.", null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_en_oficina_importadora',
            field=models.DateTimeField(blank=True, help_text="Timestamp when estado_logistico transitioned to 'en_oficina_importadora'.", null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_en_viaje',
            field=models.DateTimeField(blank=True, help_text="Timestamp when estado_logistico transitioned to 'viajando'.", null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_estimada_llegada',
            field=models.DateField(blank=True, help_text='ETA: auto-computed as fecha_compra + 15 business days (Mon-Fri). Editable.', null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True),
        ),
    ]
