# Generated by Django 5.2.6 on 2026-05-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_ordencompra_created_at_ordencompra_fecha_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='costo_importacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Import costs in COP (optional). Set in COP via the bulk import upload.', max_digits=14, null=True),
        ),
    ]
