# Generated by Django 5.2.6 on 2026-05-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0015_costos_a_cop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='costo_compra',
            field=models.DecimalField(decimal_places=2, help_text='Purchase cost in COP. Forms may accept the value in USD for convenience and convert before saving.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='impuesto_importacion',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculated as porcentaje_impuesto% of costo_compra (in COP, same currency as costo_compra)', max_digits=14),
        ),
    ]
