# Generated by Django 5.2.6 on 2026-05-08 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0020_producto_nombre_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True)),
                ('chat_id', models.CharField(help_text='Telegram chat_id (string to keep precision)', max_length=64, unique=True)),
                ('telegram_username', models.CharField(blank=True, default='', help_text='@handle of the user who subscribed (may be empty)', max_length=120)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, help_text='First time we saw this chat')),
            ],
            options={
                'verbose_name': 'Telegram Subscriber',
                'verbose_name_plural': 'Telegram Subscribers',
                'ordering': ['-first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustedSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True)),
                ('username', models.CharField(help_text='eBay seller username, lowercased on save', max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, default='', help_text='Optional pretty name for the UI', max_length=120)),
                ('notes', models.TextField(blank=True, default='', help_text='Operator notes about this seller')),
            ],
            options={
                'verbose_name': 'Trusted Seller',
                'verbose_name_plural': 'Trusted Sellers',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='MonitoredProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True)),
                ('nickname', models.CharField(help_text="Operator-friendly label, e.g. 'Acer Nitro V 5050'", max_length=160)),
                ('ebay_url', models.URLField(help_text='Full eBay listing URL', max_length=2048)),
                ('ebay_item_id', models.CharField(db_index=True, help_text='Legacy item ID extracted from ebay_url', max_length=32)),
                ('max_price_cop', models.DecimalField(decimal_places=2, help_text='All-in price ceiling in COP', max_digits=14)),
                ('last_seen_available_at', models.DateTimeField(blank=True, help_text='Last time the listing was seen with stock', null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, help_text='Last time we sent a notification for this product', null=True)),
                ('last_notified_price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='USD price quoted in the last notification', max_digits=10, null=True)),
                ('last_known_price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Most recent USD price observed', max_digits=10, null=True)),
                ('last_known_seller', models.CharField(blank=True, default='', help_text='Most recent seller.username observed', max_length=100)),
                ('producto_catalogo', models.ForeignKey(blank=True, help_text='Optional link to the catalog product, when the deal restocks an existing SKU', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitored_deals', to='products.producto')),
                ('usuario_ultima_modificacion', models.ForeignKey(blank=True, help_text='Last user who modified this monitored product', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitored_products_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitored Product',
                'verbose_name_plural': 'Monitored Products',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('product', 'Product')], max_length=20)),
                ('paused_until', models.DateTimeField(blank=True, help_text='When the pause expires; null means indefinite', null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_via', models.CharField(choices=[('ui', 'UI'), ('telegram', 'Telegram'), ('admin', 'Admin')], default='ui', max_length=20)),
                ('monitored_product', models.ForeignKey(blank=True, help_text="Required when scope='product', null when scope='global'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='deal_watcher.monitoredproduct')),
            ],
            options={
                'verbose_name': 'Notification Pause',
                'verbose_name_plural': 'Notification Pauses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('was_available', models.BooleanField(default=False)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trm_used', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_cop_calculated', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('seller_username', models.CharField(blank=True, default='', max_length=100)),
                ('seller_is_trusted', models.BooleanField(default=False)),
                ('triggered_notification', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('monitored_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_checks', to='deal_watcher.monitoredproduct')),
            ],
            options={
                'verbose_name': 'Price Check',
                'verbose_name_plural': 'Price Checks',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['monitored_product', '-checked_at'], name='deal_watche_monitor_ecb696_idx')],
            },
        ),
    ]
