# Generated by Django 5.2.6 on 2026-05-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_watcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredproduct',
            name='ebay_item_id',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-extracted from ebay_url on save', max_length=32),
        ),
    ]
