# Generated by Django 5.2.6 on 2026-05-21 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_watcher', '0002_alter_monitoredproduct_ebay_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True)),
                ('hora_inicio_activa', models.TimeField(default=datetime.time(7, 0), help_text='Inicio de la franja activa (hora Colombia, inclusivo).')),
                ('hora_fin_activa', models.TimeField(default=datetime.time(1, 0), help_text='Fin de la franja activa (hora Colombia, exclusivo). Puede ser menor que el inicio para cruzar medianoche.')),
                ('llamados_diarios_objetivo', models.PositiveIntegerField(default=5000, help_text='Presupuesto diario de llamadas a eBay (tope eBay = 5000).')),
                ('reserva_otros_llamados', models.PositiveIntegerField(default=200, help_text='Llamadas reservadas para otras tareas (precios Bajo Pedido). Se restan del presupuesto del notificador.')),
            ],
            options={
                'verbose_name': 'Configuración del Notificador',
                'verbose_name_plural': 'Configuración del Notificador',
            },
        ),
        migrations.CreateModel(
            name='UsoDiarioNotificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True, help_text='Fecha (Colombia) del inicio del período de presupuesto.', unique=True)),
                ('llamados_usados', models.PositiveIntegerField(default=0, help_text='Llamadas reales a eBay consumidas en el período.')),
                ('ciclos_ejecutados', models.PositiveIntegerField(default=0, help_text='Veces que el notificador efectivamente corrió en el período.')),
                ('ultima_ejecucion_at', models.DateTimeField(blank=True, help_text='Última corrida efectiva del notificador en el período.', null=True)),
            ],
            options={
                'verbose_name': 'Uso Diario del Notificador',
                'verbose_name_plural': 'Uso Diario del Notificador',
                'ordering': ['-dia'],
            },
        ),
    ]
