# Generated by Django 5.2.6 on 2026-05-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_watcher', '0003_configuracionnotificador_usodiarionotificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usodiarionotificador',
            name='llamados_reserva_usados',
            field=models.IntegerField(default=0, help_text='eBay calls consumed from reserva_otros_llamados by non-notifier tasks (e.g. bajo-pedido sync). Telemetry only; NOT used by should_run_now pacing.'),
        ),
    ]
