# Generated by Django 5.2.6 on 2026-06-10 22:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.DecimalField(decimal_places=2, default=Decimal('45000000'), help_text='Capital inicial del banco (mes 0).', max_digits=14)),
                ('ea', models.DecimalField(decimal_places=6, default=Decimal('0.1996'), help_text='Tasa Efectiva Anual (p.ej. 0.1996).', max_digits=8)),
                ('i_m', models.DecimalField(decimal_places=12, default=Decimal('0.015281263150'), help_text='Tasa mensual equivalente = (1+EA)^(1/12)-1. Derivable de EA.', max_digits=14)),
                ('plazo', models.PositiveIntegerField(default=48, help_text='Número total de cuotas (meses).')),
                ('dia_corte', models.PositiveIntegerField(default=11, help_text='Día de corte de cada mes (cobro del 2% y cuota).')),
                ('mes_renegociacion', models.PositiveIntegerField(default=2, help_text='Mes en que el saldo se parte en amigo/dueño.')),
                ('comision_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0200'), help_text='Comisión del amigo por corte (p.ej. 0.02 = 2%).', max_digits=6)),
                ('saldo_dueno', models.DecimalField(decimal_places=2, default=Decimal('5000000'), help_text='Saldo que conserva el dueño tras renegociar.', max_digits=14)),
                ('saldo_amigo_reneg', models.DecimalField(decimal_places=2, default=Decimal('40000000'), help_text='Saldo nominal del amigo al renegociar (informativo).', max_digits=14)),
                ('fecha_primer_corte', models.DateField(help_text='Fecha del corte del mes 1 (día de corte del primer período).')),
                ('activa', models.BooleanField(default=True, help_text='Configuración vigente que usa el motor.')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración de préstamo',
                'verbose_name_plural': 'Configuraciones de préstamo',
                'db_table': 'prestamo_configuracion',
            },
        ),
        migrations.CreateModel(
            name='PeriodoCalculado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(unique=True)),
                ('datos', models.JSONField(help_text="{'amigo': {...}, 'dueno': {...}, 'banco': {...}} redondeado.")),
                ('generado_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Período calculado',
                'verbose_name_plural': 'Períodos calculados',
                'db_table': 'prestamo_periodo_calculado',
                'ordering': ['mes'],
            },
        ),
        migrations.CreateModel(
            name='Tramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('amigo', 'Amigo'), ('dueno', 'Dueño')], max_length=10, unique=True)),
                ('saldo_vigente', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cuota_vigente', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Tramo',
                'verbose_name_plural': 'Tramos',
                'db_table': 'prestamo_tramo',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('borrar', 'Borrar')], max_length=10)),
                ('modelo', models.CharField(max_length=50)),
                ('objeto_id', models.CharField(blank=True, default='', max_length=50)),
                ('valores_antes', models.JSONField(blank=True, null=True)),
                ('valores_despues', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_prestamo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'db_table': 'prestamo_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cuota_amigo', 'Cuota amigo'), ('cuota_dueno', 'Cuota dueño'), ('abono_amigo', 'Abono amigo'), ('abono_dueno', 'Abono dueño'), ('comision_2pct', 'Comisión 2%')], max_length=20)),
                ('tramo', models.CharField(choices=[('amigo', 'Amigo'), ('dueno', 'Dueño')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField(help_text='Fecha del movimiento.')),
                ('nota', models.TextField(blank=True, default='')),
                ('comprobante_url', models.URLField(blank=True, default='', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_prestamo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'prestamo_movimiento',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
