# Generated by Django 5.2.6 on 2026-03-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('client_document', models.CharField(max_length=50)),
                ('client_phone', models.CharField(max_length=30)),
                ('client_address', models.CharField(max_length=300)),
                ('client_email', models.EmailField(max_length=254)),
                ('concepto', models.CharField(choices=[('venta', 'Venta'), ('separacion', 'Separación')], max_length=20)),
                ('item', models.CharField(choices=[('laptop', 'Laptop'), ('tarjeta_grafica', 'Tarjeta Gráfica'), ('hardware', 'Hardware'), ('pc_mesa', 'PC de Mesa')], max_length=30)),
                ('serial_item', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], max_length=30)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('email_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
