# Generated by Django 5.2.6 on 2026-03-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('nombre_completo', models.CharField(help_text='Full name of the customer', max_length=200)),
                ('cedula', models.CharField(help_text='Unique identification document', max_length=50, unique=True)),
                ('celular', models.CharField(help_text='Phone number', max_length=30)),
                ('correo', models.EmailField(help_text='Email address', max_length=254, unique=True)),
                ('direccion', models.CharField(help_text='Physical address', max_length=300)),
                ('ciudad', models.CharField(help_text='City', max_length=100)),
                ('departamento', models.CharField(help_text='Department/Region', max_length=100)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
