# Generated by Django 5.2.6 on 2026-03-15 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_campoproducto_proveedor_tipoproducto_and_more'),
        ('purchases', '0001_initial'),
        ('sales', '0002_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudBajoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('condicion', models.CharField(choices=[('nuevo', 'New'), ('open_box', 'Open Box'), ('refurbished', 'Refurbished'), ('usado', 'Used')], help_text='Desired condition of the product', max_length=20)),
                ('valor_abono', models.DecimalField(decimal_places=2, help_text='Initial payment/deposit from customer', max_digits=14)),
                ('fecha_solicitud', models.DateField(auto_now_add=True, help_text='Date when customer requested the product')),
                ('fecha_maxima_compra', models.DateField(help_text='Deadline for the purchase to be completed')),
                ('estado', models.CharField(choices=[('por_comprar', 'Pending Purchase'), ('activa', 'Active'), ('completada', 'Completed'), ('expirada', 'Expired'), ('cancelada', 'Cancelled')], default='por_comprar', help_text='Current status of the request', max_length=20)),
                ('cliente', models.ForeignKey(help_text='Customer requesting this product', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_bajo_pedido', to='sales.cliente')),
                ('orden_compra', models.OneToOneField(blank=True, help_text='Associated purchase order (set when order is created)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_bajo_pedido', to='purchases.ordencompra')),
                ('producto', models.ForeignKey(help_text='Product the customer is requesting', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_bajo_pedido', to='products.producto')),
                ('usuario_ultima_modificacion', models.ForeignKey(help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_bajo_pedido_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Back Order Request',
                'verbose_name_plural': 'Customer Back Order Requests',
                'ordering': ['-fecha_solicitud'],
                'unique_together': {('producto', 'condicion', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='Separacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('valor_abono', models.DecimalField(decimal_places=2, help_text='Deposit paid for the hold', max_digits=14)),
                ('fecha_separacion', models.DateField(auto_now_add=True, help_text='Date when the hold was created')),
                ('fecha_maxima_compra', models.DateField(help_text='Deadline for customer to complete purchase')),
                ('estado', models.CharField(choices=[('activa', 'Active'), ('expirada', 'Expired'), ('cancelada', 'Cancelled'), ('completada', 'Completed')], default='activa', help_text='Current status of the hold', max_length=20)),
                ('cliente', models.ForeignKey(help_text='Customer holding this unit', on_delete=django.db.models.deletion.PROTECT, related_name='separaciones', to='sales.cliente')),
                ('unidad_producto', models.ForeignKey(help_text='Specific unit being held', on_delete=django.db.models.deletion.PROTECT, related_name='separaciones', to='products.unidadproducto')),
                ('usuario_ultima_modificacion', models.ForeignKey(help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='separaciones_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hold/Separation',
                'verbose_name_plural': 'Holds/Separations',
                'ordering': ['-fecha_separacion'],
                'unique_together': {('unidad_producto', 'cliente')},
            },
        ),
    ]
