# Generated by Django 5.2.6 on 2026-03-15 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_campoproducto_proveedor_tipoproducto_and_more'),
        ('sales', '0003_productobajopedido_separacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('nombre', models.CharField(help_text='City name', max_length=100)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('nombre', models.CharField(help_text='Department name', max_length=100, unique=True)),
                ('codigo', models.CharField(blank=True, help_text='Optional department code', max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.ForeignKey(help_text='City where the customer is located', on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='sales.ciudad'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(help_text='Department this city belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='ciudades', to='sales.departamento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='departamento',
            field=models.ForeignKey(help_text='Department where the customer is located', on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='sales.departamento'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Date and time of the sale')),
                ('notas', models.TextField(blank=True, help_text='Optional notes about the sale', null=True)),
                ('cliente', models.ForeignKey(help_text='Customer making the purchase', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='sales.cliente')),
                ('separacion', models.ForeignKey(blank=True, help_text='Associated hold/separation if this sale originated from one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='sales.separacion')),
                ('usuario_ultima_modificacion', models.ForeignKey(help_text='Last user who modified this sale', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('url', models.URLField(help_text='URL to the receipt (Drive, S3, etc.)', max_length=500)),
                ('fecha_documento', models.DateField(blank=True, help_text='Date the receipt was generated (optional)', null=True)),
                ('separacion', models.OneToOneField(blank=True, help_text='Associated hold (if receipt is for a separation)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recibo', to='sales.separacion')),
                ('venta', models.OneToOneField(blank=True, help_text='Associated sale (if receipt is for a sale)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recibo', to='sales.venta')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ciudad',
            unique_together={('nombre', 'departamento')},
        ),
        migrations.CreateModel(
            name='ItemVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Price at the time of sale (snapshot)', max_digits=14)),
                ('unidad_producto', models.ForeignKey(help_text='Specific unit being sold', on_delete=django.db.models.deletion.PROTECT, related_name='items_venta', to='products.unidadproducto')),
                ('venta', models.ForeignKey(help_text='Sale this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.venta')),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sale Items',
                'unique_together': {('venta', 'unidad_producto')},
            },
        ),
    ]
