# Generated by Django 5.2.6 on 2026-03-17 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_campoproducto_proveedor_tipoproducto_and_more'),
        ('purchases', '0005_remove_ordencompra_variante_producto_and_more'),
        ('sales', '0004_ciudad_departamento_alter_cliente_ciudad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_entrega',
            field=models.CharField(choices=[('por_entregar', 'Pending Delivery'), ('entregado', 'Delivered')], default='por_entregar', help_text='Delivery status of the sale', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, help_text='Date and time when the sale was delivered', null=True),
        ),
    ]
