# Generated by Django 5.2.6 on 2026-03-24 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_invoice_refactor_remove_recibo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cliente',
            field=models.ForeignKey(help_text='Customer this invoice belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.cliente'),
        ),
    ]
