# Generated by Django 5.2.6 on 2026-04-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_invoice_options_remove_invoice_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='item',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
