# Generated by Django 5.2.6 on 2026-04-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_invoice_item_remove_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True),
        ),
        migrations.AddField(
            model_name='itemventa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True),
        ),
        migrations.AddField(
            model_name='itemventa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True),
        ),
        migrations.AddField(
            model_name='separacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True),
        ),
        migrations.AddField(
            model_name='separacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True),
        ),
        migrations.AddField(
            model_name='solicitudbajopedido',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True),
        ),
        migrations.AddField(
            model_name='solicitudbajopedido',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='canal',
            field=models.CharField(choices=[('tienda_fisica', 'Tienda física'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('otro', 'Otro')], default='tienda_fisica', help_text='Channel through which the sale was closed', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='costo_envio_local',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shipping cost inside Colombia absorbed by the business. 0 if local pickup.', max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_entrega',
            field=models.CharField(choices=[('local', 'Recogida en tienda'), ('envio', 'Envío a domicilio')], default='local', help_text='Delivery modality agreed with the customer', max_length=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True),
        ),
    ]
