# Generated by Django 5.2.6 on 2026-05-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_ciudad_created_at_ciudad_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_entrega_envio',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the carrier confirmed delivery (only for tipo_entrega=envio).', null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the sale was dispatched (only for tipo_entrega=envio).', null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_guia',
            field=models.CharField(blank=True, default='', help_text='Tracking number provided by the carrier. Empty for in-store pickups.', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='transportadora',
            field=models.CharField(blank=True, default='', help_text='Carrier / shipping company. Empty when delivery is in-store pickup.', max_length=100),
        ),
    ]
