# Generated by Django 5.2.6 on 2025-09-18 04:59

import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Brand's name", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL slug, auto-generated', max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Categorys name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL slug, auto-generated', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category', null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Full name of the product model', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Slug for the URL, it is automatically generated', max_length=280, unique=True)),
                ('long_description', models.TextField(help_text='Detailed description and specifications of the product')),
                ('specs', models.JSONField(default=dict, help_text='Product specifications in JSON format')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user_last_modified', models.ForeignKey(help_text='Last user who modified this product', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(help_text='Brand to which the product belongs', on_delete=django.db.models.deletion.PROTECT, related_name='base_products', to='products.brand')),
                ('categories', models.ManyToManyField(help_text='Categories to which the product belongs', related_name='base_products', to='products.category')),
            ],
            options={
                'verbose_name': 'Base Product',
                'verbose_name_plural': 'Base Products',
                'ordering': ['-user_last_modified'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text="Product' image", upload_to=products.models.get_image_upload_path)),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para la imagen (SEO)', max_length=255, null=True)),
                ('product_variant', models.ForeignKey(help_text='Variant to which the image belongs', on_delete=django.db.models.deletion.ProtectedError, related_name='images', to='products.baseproduct')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(help_text='Selling price of the variant')),
                ('description', models.TextField(help_text='Specific description for this variant (e.g., ‘Open box, unused equipment’)', null=True)),
                ('condition', models.CharField(choices=[('nuevo', 'Nuevo'), ('open_box', 'Open Box'), ('refurbished', 'Refurbished'), ('usado', 'Usado')], default='nuevo', help_text='Condition of the product', max_length=20)),
                ('stock_status', models.CharField(choices=[('en_stock', 'En Stock'), ('en_camino', 'En Camino'), ('por_importacion', 'Por Importación'), ('sin_stock', 'Sin Stock')], default='en_stock', help_text='Product stock status', max_length=20)),
                ('is_publishied', models.BooleanField(default=True, help_text='Indicates whether the variant is visible in the store')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('base_product', models.ForeignKey(help_text='Base product to which this variant belongs', on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='products.baseproduct')),
                ('user_last_modified', models.ForeignKey(help_text='Last user who modified this variant', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['price', 'condition'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_price', models.IntegerField(help_text='Final price with discount applied')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether the discount is active')),
                ('product_variant', models.OneToOneField(help_text='Variant that has this discount', on_delete=django.db.models.deletion.PROTECT, related_name='discount', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
    ]
