# Generated by Django 5.2.6 on 2025-09-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL slug, auto-generated', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True, help_text='Specific description for this variant (e.g., ‘Open box, unused equipment’)', null=True),
        ),
    ]
