# Generated by Django 5.2.6 on 2025-10-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_slug_alter_productvariant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='brand',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='image',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True, help_text="Specific description for this variant (e.g., 'Open box, unused equipment')", null=True),
        ),
    ]
