# Generated by Django 5.2.6 on 2025-10-11 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_baseproduct_active_brand_active_category_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product_variant',
            new_name='base_product',
        ),
    ]
