# Generated by Django 5.2.6 on 2025-10-13 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_product_variant_image_base_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='description',
        ),
    ]
