# Generated by Django 5.2.6 on 2025-10-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productvariant_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='is_publishied',
            new_name='is_published',
        ),
    ]
