# Generated by Django 5.2.6 on 2026-02-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_is_publishied_productvariant_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order of the image'),
        ),
    ]
