# Generated by Django 5.2.6 on 2026-03-17 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_image_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('nombre', models.CharField(help_text='Field name (e.g. RAM, GPU Model)', max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('texto', 'Text'), ('numero', 'Number'), ('booleano', 'Boolean')], default='texto', help_text='Data type of this field', max_length=20)),
                ('required', models.BooleanField(default=False, help_text='Whether this field must be filled in when creating or editing a product')),
            ],
            options={
                'verbose_name': 'Product Field',
                'verbose_name_plural': 'Product Fields',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('nombre', models.CharField(help_text='Supplier name', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL slug, auto-generated', max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('nombre', models.CharField(help_text='Product type name', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Optional description of the product type', null=True)),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='baseproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='baseproduct',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='baseproduct',
            name='user_last_modified',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='base_product',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='user_last_modified',
        ),
        migrations.AddField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text="Category's name", max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('nombre', models.CharField(help_text='Full product name / model', max_length=255)),
                ('descripcion', models.TextField(help_text='Detailed product description (supports long text with formatting)')),
                ('marca', models.ForeignKey(help_text='Brand of this product', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='products.brand')),
                ('usuario_ultima_modificacion', models.ForeignKey(help_text='Last user who modified this product', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('url', models.ImageField(help_text='Product image file', upload_to='products/images/')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Display order of this image')),
                ('producto', models.ForeignKey(help_text='Product this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='products.producto')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('condicion', models.CharField(choices=[('nuevo', 'New'), ('open_box', 'Open Box'), ('refurbished', 'Refurbished'), ('usado', 'Used')], help_text='Condition of units this discount applies to', max_length=20)),
                ('precio_descuento', models.DecimalField(decimal_places=2, help_text='Discounted sale price (COP)', max_digits=14)),
                ('fecha_inicio', models.DateField(help_text='Date from which the discount is valid')),
                ('fecha_fin', models.DateField(help_text='Date until which the discount is valid')),
                ('producto', models.ForeignKey(help_text='Product that receives this discount', on_delete=django.db.models.deletion.PROTECT, related_name='descuentos', to='products.producto')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'unique_together': {('producto', 'condicion')},
            },
        ),
        migrations.CreateModel(
            name='ProductoCampoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, help_text="Value when campo_producto.tipo = 'texto'", null=True)),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=6, help_text="Value when campo_producto.tipo = 'numero'", max_digits=20, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, help_text="Value when campo_producto.tipo = 'booleano'", null=True)),
                ('campo_producto', models.ForeignKey(help_text='Dynamic field definition', on_delete=django.db.models.deletion.PROTECT, related_name='campo_valores', to='products.campoproducto')),
                ('producto', models.ForeignKey(help_text='Product this value belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='campo_valores', to='products.producto')),
            ],
            options={
                'verbose_name': 'Product Field Value',
                'verbose_name_plural': 'Product Field Values',
                'unique_together': {('producto', 'campo_producto')},
            },
        ),
        migrations.CreateModel(
            name='ProductoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(help_text='Category', on_delete=django.db.models.deletion.CASCADE, related_name='producto_categorias', to='products.category')),
                ('producto', models.ForeignKey(help_text='Product', on_delete=django.db.models.deletion.CASCADE, related_name='producto_categorias', to='products.producto')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'unique_together': {('producto', 'categoria')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(help_text='Categories this product belongs to', related_name='productos', through='products.ProductoCategoria', to='products.category'),
        ),
        migrations.CreateModel(
            name='BajoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('condicion', models.CharField(choices=[('nuevo', 'New'), ('open_box', 'Open Box'), ('refurbished', 'Refurbished'), ('usado', 'Used')], help_text='Physical condition for on-demand sourcing', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Price updated daily by Celery via eBay formula', max_digits=14)),
                ('enlace_proveedor', models.URLField(blank=True, help_text='eBay item URL (optional)', max_length=2048, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Active'), ('sin_existencias', 'Out of Stock'), ('inactivo', 'Inactive')], default='activo', help_text='Availability status for on-demand sourcing', max_length=20)),
                ('usuario_ultima_modificacion', models.ForeignKey(help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bajo_pedidos_modificados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(help_text='Product available on-demand', on_delete=django.db.models.deletion.PROTECT, related_name='bajo_pedidos', to='products.producto')),
                ('proveedor', models.ForeignKey(blank=True, help_text='Supplier (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajo_pedidos', to='products.proveedor')),
            ],
            options={
                'verbose_name': 'On-Demand Product',
                'verbose_name_plural': 'On-Demand Products',
                'ordering': ['producto', 'condicion'],
                'unique_together': {('producto', 'condicion')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(help_text='Product type that defines which dynamic fields apply', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='products.tipoproducto'),
        ),
        migrations.CreateModel(
            name='TipoProductoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Display order of this field within the product type')),
                ('required', models.BooleanField(default=False, help_text='Whether this field is required when creating or editing a product of this type')),
                ('campo_producto', models.ForeignKey(help_text='Dynamic field linked to this product type', on_delete=django.db.models.deletion.CASCADE, related_name='tipo_producto_campos', to='products.campoproducto')),
                ('tipo_producto', models.ForeignKey(help_text='Product type this field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tipo_producto_campos', to='products.tipoproducto')),
            ],
            options={
                'verbose_name': 'Product Type Field',
                'verbose_name_plural': 'Product Type Fields',
                'ordering': ['orden'],
                'unique_together': {('tipo_producto', 'campo_producto')},
            },
        ),
        migrations.CreateModel(
            name='UnidadProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('serial', models.CharField(help_text='Unique serial number of this unit', max_length=100, unique=True)),
                ('condicion', models.CharField(choices=[('nuevo', 'New'), ('open_box', 'Open Box'), ('refurbished', 'Refurbished'), ('usado', 'Used')], help_text='Physical condition of this unit', max_length=20)),
                ('estado_venta', models.CharField(choices=[('sin_vender', 'Not Sold'), ('separado', 'On Hold'), ('vendido', 'Sold'), ('por_encargo', 'On Order'), ('entregado_garantia', 'Warranty Delivery'), ('danado', 'Damaged'), ('solicitud_metodo_aliado', 'Pending Trade-in')], default='sin_vender', help_text='Commercial status of this unit', max_length=30)),
                ('estado_producto', models.CharField(choices=[('en_stock', 'In Stock'), ('viajando', 'In Transit'), ('por_comprar', 'Pending Purchase'), ('por_entregar', 'Pending Delivery'), ('entregado', 'Delivered'), ('por_reparar', 'Pending Repair'), ('en_reparacion', 'In Repair')], default='en_stock', help_text='Physical / logistic state of this unit', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Individual sale price for this unit (COP)', max_digits=14)),
                ('producto', models.ForeignKey(help_text='Product this unit belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='products.producto')),
                ('usuario_ultima_modificacion', models.ForeignKey(help_text='Last user who modified this unit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Unit',
                'verbose_name_plural': 'Product Units',
                'ordering': ['serial'],
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='BaseProduct',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
