# Generated by Django 5.2.6 on 2026-03-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_category_productocategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campoproducto',
            name='required',
        ),
        migrations.AddField(
            model_name='tipoproductocampo',
            name='is_filter',
            field=models.BooleanField(default=False, help_text='Define if a field is a filterable attribute (e.g. for faceted search)'),
        ),
    ]
