# Generated by Django 5.2.6 on 2026-04-06 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_campoproducto_required_and_more'),
        ('sales', '0009_invoice_item_remove_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadproducto',
            name='ciudad_envio_metodo_aliado',
            field=models.CharField(blank=True, default='', help_text='Destination city for método aliado shipment (free text)', max_length=200),
        ),
        migrations.AddField(
            model_name='unidadproducto',
            name='cliente_metodo_aliado',
            field=models.ForeignKey(blank=True, help_text='Client associated with método aliado request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_metodo_aliado', to='sales.cliente'),
        ),
        migrations.AlterField(
            model_name='bajopedido',
            name='condicion',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('open_box', 'Open Box'), ('refurbished', 'Reacondicionado'), ('usado', 'Usado')], help_text='Physical condition for on-demand sourcing', max_length=20),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='condicion',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('open_box', 'Open Box'), ('refurbished', 'Reacondicionado'), ('usado', 'Usado')], help_text='Condition of units this discount applies to', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidadproducto',
            name='condicion',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('open_box', 'Open Box'), ('refurbished', 'Reacondicionado'), ('usado', 'Usado')], help_text='Physical condition of this unit', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidadproducto',
            name='estado_producto',
            field=models.CharField(choices=[('en_stock', 'En Oficina'), ('viajando', 'In Transit'), ('por_comprar', 'Pending Purchase'), ('por_entregar', 'Pending Delivery'), ('entregado', 'Delivered'), ('por_reparar', 'Pending Repair'), ('en_reparacion', 'In Repair')], default='en_stock', help_text='Physical / logistic state of this unit', max_length=20),
        ),
    ]
