# Generated by Django 5.2.6 on 2026-04-07 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_unidad_metodo_aliado_fields'),
        ('sales', '0009_invoice_item_remove_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadproducto',
            name='cliente_garantia',
            field=models.ForeignKey(blank=True, help_text='Client associated with warranty delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_garantia', to='sales.cliente'),
        ),
    ]
