# Generated by Django 5.2.6 on 2026-04-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_unidad_cliente_garantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadproducto',
            name='descripcion_dano',
            field=models.TextField(blank=True, default='', help_text='Description of the reported damage (if applicable)'),
        ),
        migrations.AddField(
            model_name='unidadproducto',
            name='fecha_reporte_dano',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the damage was reported', null=True),
        ),
    ]
