# Generated by Django 5.2.6 on 2026-04-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_unidadproducto_descripcion_dano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadproducto',
            name='estado_producto',
            field=models.CharField(choices=[('en_stock', 'En Oficina'), ('viajando', 'Viajando'), ('por_comprar', 'Por Comprar'), ('por_entregar', 'Por Entregar'), ('entregado', 'Entregado'), ('por_reparar', 'Por Reparar'), ('en_reparacion', 'En Reparación')], default='en_stock', help_text='Physical / logistic state of this unit', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidadproducto',
            name='estado_venta',
            field=models.CharField(choices=[('sin_vender', 'Sin Vender'), ('separado', 'Separado'), ('vendido', 'Vendido'), ('por_encargo', 'Por Encargo'), ('entregado_garantia', 'Entregado por Garantía'), ('danado', 'Dañado'), ('solicitud_metodo_aliado', 'Solicitud Método Aliado')], default='sin_vender', help_text='Commercial status of this unit', max_length=30),
        ),
    ]
