# Generated by Django 5.2.6 on 2026-04-16 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_unidadproducto_estado_producto_and_more'),
        ('sales', '0009_invoice_item_remove_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadproducto',
            name='fecha_entrega_metodo_aliado',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the unit was delivered', null=True),
        ),
        migrations.AddField(
            model_name='unidadproducto',
            name='fecha_envio_metodo_aliado',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the unit was shipped', null=True),
        ),
        migrations.AddField(
            model_name='unidadproducto',
            name='fecha_solicitud_metodo_aliado',
            field=models.DateTimeField(blank=True, help_text='Timestamp when método aliado was requested', null=True),
        ),
        migrations.AddField(
            model_name='unidadproducto',
            name='notas_metodo_aliado',
            field=models.TextField(blank=True, default='', help_text='Additional notes about the método aliado request'),
        ),
        migrations.AddField(
            model_name='unidadproducto',
            name='numero_guia_metodo_aliado',
            field=models.CharField(blank=True, default='', help_text='Shipping tracking number', max_length=100),
        ),
        migrations.AddField(
            model_name='unidadproducto',
            name='transportadora_metodo_aliado',
            field=models.CharField(blank=True, default='', help_text='Carrier / shipping company', max_length=100),
        ),
        migrations.RemoveField(
            model_name='unidadproducto',
            name='ciudad_envio_metodo_aliado',
        ),
        migrations.AddField(
            model_name='unidadproducto',
            name='ciudad_envio_metodo_aliado',
            field=models.ForeignKey(blank=True, help_text='Destination city for método aliado shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_metodo_aliado', to='sales.ciudad'),
        ),
    ]
