# Generated by Django 5.2.6 on 2026-04-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_unidadproducto_fecha_entrega_metodo_aliado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajopedido',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True),
        ),
        migrations.AddField(
            model_name='bajopedido',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True),
        ),
        migrations.AddField(
            model_name='campoproducto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True),
        ),
        migrations.AddField(
            model_name='campoproducto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True),
        ),
        migrations.AddField(
            model_name='descuento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True),
        ),
        migrations.AddField(
            model_name='descuento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True),
        ),
        migrations.AddField(
            model_name='tipoproducto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True),
        ),
        migrations.AddField(
            model_name='tipoproducto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True),
        ),
        migrations.AddField(
            model_name='unidadproducto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True),
        ),
        migrations.AddField(
            model_name='unidadproducto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True),
        ),
    ]
