# Generated by Django 5.2.6 on 2026-05-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_bajopedido_created_at_bajopedido_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadproducto',
            name='estado_producto',
            field=models.CharField(choices=[('en_stock', 'En Oficina'), ('viajando', 'Viajando'), ('en_oficina_importadora', 'En Oficina Importadora'), ('por_comprar', 'Por Comprar'), ('por_entregar', 'Por Entregar'), ('entregado', 'Entregado'), ('por_reparar', 'Por Reparar'), ('en_reparacion', 'En Reparación')], default='en_stock', help_text='Physical / logistic state of this unit', max_length=30),
        ),
    ]
