# Generated by Django 5.2.6 on 2026-05-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_unidades_en_oficina_importadora'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproductocampo',
            name='icono_slug',
            field=models.CharField(blank=True, default='', help_text="Slug of the icon shown next to the value on the promo card (e.g. 'cpu', 'gpu', 'ram'). Maps to /promo-assets/icons/<slug>.svg in the frontend", max_length=40),
        ),
        migrations.AddField(
            model_name='tipoproductocampo',
            name='mostrar_en_promo',
            field=models.BooleanField(default=False, help_text='Whether this field is rendered on the promotional card image for products of this type'),
        ),
        migrations.AddField(
            model_name='tipoproductocampo',
            name='orden_promo',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order of this field on the promotional card (top-to-bottom). Only relevant when mostrar_en_promo=True'),
        ),
    ]
