# Generated by Django 5.2.6 on 2026-05-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_tipoproductocampo_promo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre_base',
            field=models.CharField(blank=True, default='', help_text="Short version of the name shown on promotional images (e.g. 'Acer Predator Helios Neo 16S'). Falls back to `nombre` when empty.", max_length=120),
        ),
    ]
