# Generated by Django 5.2.6 on 2026-05-22 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_producto_nombre_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajopedido',
            name='disponibilidad_ebay',
            field=models.CharField(choices=[('disponible', 'Available'), ('agotado', 'Sold Out'), ('desconocido', 'Unknown')], default='desconocido', help_text='Last known eBay availability. Written ONLY by the sync task', max_length=20),
        ),
        migrations.AddField(
            model_name='bajopedido',
            name='ebay_legacy_id',
            field=models.CharField(blank=True, db_index=True, help_text='eBay legacy item ID parsed from enlace_proveedor; used by the daily sync', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bajopedido',
            name='fallos_consecutivos',
            field=models.IntegerField(default=0, help_text='Consecutive failed eBay lookups; reset to 0 on a successful sync'),
        ),
        migrations.AddField(
            model_name='bajopedido',
            name='ultimo_sync_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last sync attempt against eBay', null=True),
        ),
        migrations.AddField(
            model_name='bajopedido',
            name='ultimo_vendedor',
            field=models.CharField(blank=True, help_text='Seller username seen on the last successful eBay sync', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SyncBajoPedidoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether this record is active or not', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this sync attempt was recorded')),
                ('was_available', models.BooleanField(default=False, help_text='Whether the eBay item was available at check time')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='eBay price in USD at check time', max_digits=10, null=True)),
                ('trm_used', models.DecimalField(blank=True, decimal_places=2, help_text='COP/USD exchange rate applied', max_digits=10, null=True)),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, help_text='BajoPedido price before this sync (COP)', max_digits=14, null=True)),
                ('precio_nuevo', models.DecimalField(blank=True, decimal_places=2, help_text='BajoPedido price after this sync (COP)', max_digits=14, null=True)),
                ('seller_username', models.CharField(blank=True, default='', help_text='eBay seller username seen at check time', max_length=100)),
                ('seller_is_trusted', models.BooleanField(default=False, help_text='Whether the seller was a trusted seller at check time')),
                ('resultado', models.CharField(choices=[('precio_subido', 'Price Raised'), ('sin_cambio', 'No Change'), ('margen_para_bajar', 'Margin To Lower'), ('agotado_seller', 'Sold Out (Seller)'), ('agotado_fallos', 'Sold Out (Consecutive Failures)'), ('fallo_ebay', 'eBay Lookup Failed'), ('sin_unidades_skip', 'Skipped (No Units)'), ('con_unidades_skip', 'Skipped (Has Units)')], help_text='Outcome of this sync attempt', max_length=30)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error detail when the sync attempt failed')),
                ('bajo_pedido', models.ForeignKey(help_text='Listing this sync attempt refers to', on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='products.bajopedido')),
            ],
            options={
                'verbose_name': 'Bajo Pedido Sync Log',
                'verbose_name_plural': 'Bajo Pedido Sync Logs',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['bajo_pedido', '-checked_at'], name='products_sy_bajo_pe_f09848_idx')],
            },
        ),
    ]
